In [6]:
import pandas as pd
from io import StringIO

# JSON formatted as an array
Data = '[{"employee_name":"james","email":"jamesz@gmail.com"}]'

# Use StringIO for a file-like object
df = pd.read_json(StringIO(Data))

print(df)

  employee_name             email
0         james  jamesz@gmail.com

In [7]:
df

  employee_name             email
0         james  jamesz@gmail.com

In [8]:
df.to_json()

'{"employee_name":{"0":"james"},"email":{"0":"jamesz@gmail.com"}}'

In [9]:
df.to_json(orient='index')

'{"0":{"employee_name":"james","email":"jamesz@gmail.com"}}'

In [10]:
df.to_json(orient='records')

'[{"employee_name":"james","email":"jamesz@gmail.com"}]'

In [11]:
url ="https://www.fdcindia.com/"

df=pd.read_html(url)

In [12]:
df

[    Sr   Plant                                         Brand name  \
 0    1   Waluj       Chloramphenicol Ophthalmic Solution 0.5% w/v
 1    2   Waluj                       Dorzolamide 2% w/v Eye drops
 2    3   Waluj     Dorzolamide 2% w/v, Timolol 0.5% w/v Eye Drops
 3    4   Waluj                                             Dorzox
 4    5   Waluj                                           Dorzox-T
 5    6   Waluj                                           Duoprost
 6    7   Waluj                      Gentamycin 0.3% Eye drops w/v
 7    8   Waluj             Latanoprost 0.005% Ophthalmic Solution
 8    9   Waluj  Latanoprost 0.005%, Timolol 0.5% Ophthalmic So...
 9   10  Sinnar                         ORS 28.4 gms (Lime flavor)
 10  11  Sinnar                    ORS 6.7 gms (Strawberry flavor)
 11  12   Waluj                                           Premoxin
 12  13   Waluj                           Timolol Maleate 0.5% w/v

                                          Generic name    Dosage Form  \
 0        Chloramphenicol Ophthalmic Solution 0.5% w/v      Eye Drops
 1                        Dorzolamide 2% w/v Eye drops      Eye Drops
 2      Dorzolamide 2% w/v, Timolol 0.5% w/v Eye Drops      Eye Drops
 3                        Dorzolamide 2% w/v Eye Drops      Eye Drops
 4           Dorzolamide 2% and Timolol 0.5% Eye Drops      Eye Drops
 5   Latanoprost 0.005% w/v, Timolol 0.5% w/v Eye D...      Eye Drops
 6                       Gentamycin 0.3% Eye drops w/v      Eye drops
 7          Latanoprost 0.005% Ophthalmic Solution w/v      Eye Drops
 8   Latanoprost 0.005%, Timolol 0.5% Ophthalmic So...      Eye Drops
 9                                        ORS 28.4 gms  Oral Granules
 10                                        ORS 6.7 gms  Oral Granules
 11                    Moxifloxacin 0.5% Eye Drops w/v      Eye Drops
 12                               Timolol Maleate 0.5%      Eye Drops

                 Strength   Pack size
 0               0.5% w/v     1x10 ml
 1                 2% w/v    1 x 5 ML
 2           2%, 0.5% w/v    1 x 5 ML
 3                 2% w/v      1x5 ml
 4           2%, 0.5% w/v      1x5 ml
 5   0.005% w/v, 0.5% w/v  1 x 2.5 ml
 6               0.3% w/v    1 x 5 ml
 7             0.005% w/v    1x2.5 ml
 8   0.005% w/v, 0.5% w/v    1x2.5 ml
 9               28.4 gms          4s
 10               6.7 gms         30s
 11              0.5% w/v      1x5 ml
 12              0.5% w/v    1 x 5 ml  ,
    Sr  Plant Brand name                  Generic name Dosage Form  Strength  \
 0   1  Waluj     Acuxim       Carboxymethyl Cellulose   Eye drops     0.50%
 1   2  Waluj     Dormol  Dorzolamide 2%, Timolol 0.5%   Eye drops  2%, 0.5%
 2   3  Waluj     Floxma                  Moxifloxacin   Eye drops     0.50%
 3   4  Waluj       Yuro            Sodium Hyaluronate   Eye drops     0.15%

     Pack size
 0      1x5 ml
 1   1 x 5 ml.
 2      1x5 ml
 3  1 x 10 ml.  ,
     Sr  Plant     Brand name                             Generic name  \
 0    1  Goa-I         Azifar           Azithromycin 500mg USP Tablets
 1    2  Baddi  Cefstalip 500            Cefuroxime Axetil Tablets USP
 2    3  Waluj       Ciprolip              Ciprofloxacin Hydrochloride
 3    4  Waluj         Dorlip                           Dorzolamide 2%
 4    5  Waluj       Dorlip-T   Dorzolamide 2%, Timolol 0.5% Eye drops
 5    6  Waluj       Eyemicin                               Gentamicin
 6    7  Waluj     Flucofarma                           Fluconazole BP
 7    8  Waluj      Glaucolip                 Timolol Maleate 0.5% w/v
 8    9  Waluj         Iobram  Brimonidine Tartrate 0.2% w/v Eye Drops
 9   10  Waluj         Iobram          Brimonidine 0.15% Eye Drops w/v
 10  11  Waluj         Moxima                             Moxifloxacin
 11  12  Waluj        Ofloxal                           Ofloxacin 0.3%
 12  13  Goa-I      Terbispor          Terbinafine Hydrochloride 250mg
 13  14  Waluj    Vista Tears          Hypromellose 0.3% w/v Eye Drops
 14  15  Waluj       Visualip                    Hypromellose 0.5% w/w

            Dosage Form      Strength                 Pack size
 0              Tablets        500 mg                      1x3T
 1   Film Coated Tablet        500 mg                     1x10T
 2            Eye Drops      0.3% w/v                    1x5 mL
 3            Eye drops        2% w/v                  1 x 5 ml
 4            Eye Drops  2%, 0.5% w/v                    1x5 ml
 5            Eye Drops      0.3% w/v                  1 x 5 ml
 6             Capsules         150mg                       1x1
 7            Eye Drops      0.5% w/v                      5 ml
 8            Eye Drops      0.2% w/v                  1 x 5 ml
 9            Eye drops     0.15% w/v                    1x5 ml
 10           Eye Drops      0.3% w/v                  1 x 5 ml
 11           Eye Drops      0.3% w/v  1x5 mL, 1x10 mL, 1x15 mL
 12             Tablets         250mg                    3 x 10
 13           Eye Drops      0.3% w/v                 1 x 10 ml
 14           Eye drops      0.3% w/v                   1x10 ml  ,
    Sr Plant                   Brand name            Generic name  Dosage Form  \
 0   1     -  Electral Ready to Drink ORS  Oral Rehydration Salts  Oral Liquid

                   Strength Pack size
 0  WHO recommended formula  1x200 ml  ,
    Sr   Plant Brand name                    Generic name    Dosage Form  \
 0   1  Sinnar    ENERZAL                              ..  Oral granules
 1   2   Goa-I     Fluren  Flunarizine Hydrochloride 10mg        Tablets

   Strength Pack size
 0        *    500 ml
 1    10 mg      1x10  ,
    Sr  Plant Brand name                           Generic name Dosage Form  \
 0   1  Goa-I    Zathrin        Azithroimycin 250mg Tablets USP     Tablets
 1   2  Goa-I  Zoxan 500  Ciprofloxacin Hydrochloride 500mg USP     Tablets

   Strength Pack size
 0   250 mg       1x6
 1   500 mg      1x10  ,
    Sr       Plant      Brand name              Generic name    Dosage Form  \
 0   1       Waluj       Allercrom       Sodium Cromoglicate      Eye drops
 1   2       Waluj        Bactigen  Gentamicin Eye/Ear Drops      Eye drops
 2   3  Zen Pharma         Cotaryl         Urea, Lactic acid          Cream
 3   4      Sinnar  Electral Forte                       ORS  Oral Granules
 4   5       Waluj      Iotim 0.5%      Timolol Maleate 0.5%      Eye drops
 5   6       Waluj         Ocuflur              Flurbiprofen      Eye drops
 6   7       Waluj           Zoxan         Ciprofloxacin Hcl      Eye drops

   Strength Pack size
 0       2%  1 x 5ml.
 1    0.30%  1 x 5ml.
 2      NaN   50 gms.
 3   30 gm.      20's
 4    0.50%  1 x 5ml.
 5    0.35%  1 x 5ml.
 6    0.30%  1 x 5ml.  ,
    Sr   Plant   Brand name Generic name    Dosage Form Strength Pack size
 0   1  Sinnar  ORS 6.7 gms  ORS 6.7 gms  Oral Granules  6.7 gms   6.7 gms,
    Sr    Plant  Brand name                        Generic name    Dosage Form  \
 0   1    Waluj   Allercrom          Sodium Cromoglicate 2% w/v      Eye Drops
 1   2   Sinnar    Electral              Oral Rehydration Salts  Oral granules
 2   3      Goa  Electral-Z  ORS 21.8 Grams , Zinc Sulfate 20mg    Oral Solids
 3   4    Waluj      Iobrim                Brimonidine Tartrate      Eye Drops
 4   5   Sinnar         ORS                                 ORS  Oral Granules
 5   6    Waluj  Vanmycetin                     Chloramphenicol      Eye drops
 6   7  Goa-III      Zioral                        Zinc Sulfate        Tablets

           Strength        Pack size
 0         0.2% w/v        1 x 10 ml
 1       21.8 grams       21.8 grams
 2  21.8 Gms & 20mg          1 x KIT
 3         0.2% w/v      1x5 ml vial
 4         20.5 Gms    1 x 20.5 gms.
 5            0.50%       1 x 10 ml.
 6             20mg  10 x 10 Tablets  ,
     Sr   Plant   Brand name  \
 0    1   Waluj    Allercrom
 1    2   Waluj     Bactigen
 2    3  Sinnar     Electral
 3    4     Goa   Electral-Z
 4    5   Waluj        Iobet
 5    6   Waluj        Iotim
 6    7   Waluj  Latanoprost
 7    8   Waluj         Mosi
 8    9   Waluj   Mycoderm-C
 9   10   Waluj       Ocudor
 10  11   Waluj     Ocudor-T
 11  12   Waluj      Ocuflur
 12  13   Waluj       Olodin
 13  14   Waluj       Plapar
 14  15   Waluj      Tearmax
 15  16   Waluj   Vanmycetin
 16  17   Goa-I      Zathrin
 17  18   Waluj           ZO
 18  19   Waluj        Zocon
 19  20   Waluj        Zoxan
 20  21   Waluj      Zoxan-D

                                          Generic name      Dosage Form  \
 0                                 Sodium Cromoglicate        Eye drops
 1                   Gentamycin 0.3% Eye/Ear drops w/v    Eye/Ear drops
 2                                                 ORS    Oral Granules
 3   ORS 21.8 + Zinc Sulfate 20mg Dispersible table...  Oral dosage Kit
 4                                       Betaxolol HCL        Eye drops
 5                  Timolol Maleate 0.5% Eye drops w/v        Eye drops
 6                                         Latanoprost        Eye drops
 7                     Moxifloxacin 0.5% w/v Eye Drops        Eye Drops
 8                      Clotrimazole 1% dusting powder  External Powder
 9                                         Dorzolamide        Eye Drops
 10                              Dorzolamide & Timolol        Eye drops
 11                                       Flurbiprofen        Eye drops
 12                               Olopatadine 0.1% w/v        Eye Drops
 13              Paracetamol 120mg/5ml oral suspension      Oral Liquid
 14                    Carboxymethylcellulose 0.5% w/v        Eye Drops
 15                                    Chloramphenicol        Eye drops
 16               Azithromycin Dihydrate 500mg Tablets          Tablets
 17                                          Ofloxacin        Eye Drops
 18                                        Fluconazole        Eye drops
 19                                  Ciprofloxacin Hcl        Eye drops
 20         Ciprofloxacin 0.3%, Dexamethesone 0.1% w/v        Eye Drops

             Strength                                          Pack size
 0                 2%                                     1 x 5 ml. Vial
 1           0.3% w/v                                           1 x 5 ml
 2           21.8 gms                                          21.8 gms.
 3   21.8 Gms , 20mg.  1 Kit contains 2 sachets of ORS 21.8 gms & 1x1...
 4              0.50%                                          1 x 5 ml.
 5           0.5% w/v                                           1 x 5 ml
 6              0.01%                                        1 x 2.5 ml.
 7           0.5% w/v                                           1 x 5 ML
 8                 1%                                          100 Grams
 9             2% w/v                                           1 x 5 ml
 10         2% & 0.5%                                           1 x 5 ml
 11             0.35%                                          1 x 5 ml.
 12          0.1% w/v                                           1 x 5 ml
 13         120mg/5ml                                         1 x 100 ml
 14          0.5% w/v                                          1 x 10 ml
 15             0.50%                                         1 x 10 ml.
 16             500mg                                               1x3T
 17          0.3% w/v                                           1 x 5 ml
 18             0.30%                                          1 x 5 ml.
 19             0.30%                                           1 x 5ml.
 20    0.3%, 0.1% w/v                                           1 x 5 mL  ,
     Sr   Plant                  Brand name  \
 0    1   Waluj         Allercrom Eye Drops
 1    2   Waluj          Bactigen Eye Drops
 2    3   Waluj            I-Lube Eye Drops
 3    4   Waluj             Iobet Eye Drops
 4    5   Waluj             Iotim Eye Drops
 5    6   Waluj             Iotim Eye Drops
 6    7   Waluj                      Moisol
 7    8   Waluj           Ocuflur Eye Drops
 8    9       -                Ocuvir cream
 9   10   Waluj           Ocuvir Suspension
 10  11   Waluj                      Plapar
 11  12   Waluj           Pyrimon Eye Drops
 12  13  Sinnar  Sel De Rehydratation Orale
 13  14   Waluj                    Vitcofol
 14  15     Goa                   Zocon 200
 15  16   Waluj             Zocon Eye Drops
 16  17   Waluj             Zoxan Eye Drops
 17  18       -      Zoxan Ophthalmic Cream

                              Generic name  Dosage Form    Strength  \
 0                         Cromolyn Sodium    Eye Drops          2%
 1                              Gentamicin    Eye Drops       0.30%
 2            Polyvinyl Alcohol + Povidone    Eye Drops  1.4% + 0.6
 3                               Betaxolol    Eye Drops       0.50%
 4                         Timolol Maleate    Eye Drops       0.50%
 5                         Timolol Maleate    Eye Drops       0.25%
 6                            Hypromellose    Eye Drops       0.70%
 7                            Flurbiprofen    Eye Drops       0.03%
 8                               Aciclovir        Cream          5%
 9                               Aciclovir        Syrup     400 mg.
 10  Paracetamol 120mg/5ml oral suspension  Oral Liquid   120mg/5ml
 11        Dexamethasone + Chloramphenicol    Eye Drops   0.1% + 1%
 12                 Oral rehydration salts       Powder     27.9 g.
 13                        Iron supplement  Oral liquid         NaN
 14                            Fluconazole      Tablets     200 mg.
 15                            Fluconazole    Eye Drops       0.30%
 16            Ciprofloxacin Hydrochloride    Eye Drops       0.30%
 17            Ciprofloxacin Hydrochloride        Cream       0.30%

            Pack size
 0     1 x 5 ml. Vial
 1     1 x 5 ml. Vial
 2    1 x 10 ml. Vial
 3     1 x 5 ml. Vial
 4      1 x 5 ml Vial
 5      1 x 5 ml Vial
 6     1 x 5 ml. Vial
 7     1 x 5 ml. Vial
 8         1 x 5 gms.
 9   1 x 60ml. Bottle
 10        1 x 100 ml
 11    1 x 5 ml. Vial
 12     1 x 27.9 gms.
 13          1x180 ml
 14     1 x 2 Tablets
 15    1 x 5 ml. Vial
 16    1 x 5 ml. Vial
 17        1 x 5 gms.  ,
     Sr    Plant              Brand name  \
 0    1    Waluj  Bactigen Eye/Ear Drops
 1    2    Waluj                Electral
 2    3   Sinnar          Electral Forte
 3    4    Waluj                   Iotim
 4    5    Goa-I                Levofast
 5    6    Waluj          Levofast Syrup
 6    7    Waluj                Mycoderm
 7    8    Waluj              Mycoderm C
 8    9    Goa-I       Orogyl-DF Tablets
 9   10    Waluj              ORS 20.5 G
 10  11    Waluj  Pyricort Eye/Ear Drops
 11  12  Goa-III                 Zathrin
 12  13  Goa-III                  Zioral
 13  14    Waluj                   Zoxan

                                      Generic name    Dosage Form     Strength  \
 0                                      Gentamicin  Eye/Ear Drops        0.30%
 1                                             ORS  Oral Granules     21.8 gms
 2                          Oral Rehydration Salts         Powder         6 g.
 3                                 Timolol Maleate      Eye drops        0.50%
 4               Levocetrizine Dihydrochloride 5mg        Tablets         5 mg
 5                   Levocetrizine Dihydrochloride          Syrup    2.5mg/5ml
 6    Salicylic Acid + Benzoic Acid Dusting Powder         Powder       100 g.
 7                                    Clotrimazole         Powder           1%
 8   Metronidazole, Diloxanide Furoate, Simethicon        Tablets      200 mg.
 9                                             ORS  Oral Granules         20.5
 10                     Gentamicin + Dexamethasone  Eye/Ear Drops  0.3% + 0.1%
 11                         Azithromycin Dihydrate        Tablets      500 mg.
 12                                   Zinc Sulfate        Tablets       20 mg.
 13                              Ciprofloxacin Hcl  Eye/Ear drops     0.3% w/v

           Pack size
 0    1 x 5 ml. Vial
 1          21.8 gms
 2        1 x 6 gms.
 3          1 x 5 ml
 4            1 x 10
 5             30 ml
 6      1 x 100 gms.
 7       1 x 75 gms.
 8    1 x 10 Tablets
 9         20.5 gms.
 10   1 x 5 ml. Vial
 11    1 x 3 Tablets
 12  10 x 10 Tablets
 13          1 x 5ml  ,
    Sr   Plant                    Brand name            Generic name  \
 0   1  Sinnar  Oral Rehydration Salts 20.5g  Oral Rehydration Salts

   Dosage Form Strength      Pack size
 0      Powder  20.5 g.  1 x 20.5 gms.  ,
    Sr    Plant Brand name Generic name    Dosage Form  Strength  Pack size
 0   1  Goa-III        ORS          ORS  Oral Granules  27.9 gms  27.9 gms.,
     Sr    Plant           Brand name  \
 0    1    Goa-I               Amodep
 1    2    Waluj             Bactigen
 2    3    Goa-I               Cinzan
 3    4   Sinnar             Electral
 4    5      Goa           Electral-Z
 5    6    Goa-I             Fungotek
 6    7    Waluj               Norzen
 7    8    Goa-I  Omeprazole capsules
 8    9    Waluj              Pyrimon
 9   10    Baddi             Zifi 200
 10  11    Baddi             Zifi 400
 11  12  Goa-III               Zioral
 12  13    Goa-I            Zocon 150
 13  14    Goa-I            Zocon 200
 14  15    Goa-I             Zocon 50

                                          Generic name    Dosage Form  \
 0                             Amlodipine Besylate 5mg        Tablets
 1                       Gentamycin 0.3% Eye Ear drops      Eye drops
 2              Cinnarizine Hydrochloride 25mg Tablets        Tablets
 3                                                 ORS  Oral Granules
 4   ORS 21.8 + Zinc Sulfate 20mg Dispersible table...    Oral.solid.
 5             Terbinafine Hydrochloride 250mg tablets        Tablets
 6                 Norfloxacin Hydrochloride Eye drops      Eye drops
 7                                 Omeprazole capsules       Capsules
 8         Chloramphenicol and Dexamethasone Eye drops      Eye drops
 9                                            Cefixime        Tablets
 10                                           Cefixime        Tablets
 11                                       Zinc Sulfate        Tablets
 12                           Fluzonazole 150 capsules       Capsules
 13                               Fluconazole capcules       Capsules
 14                               Fluconazole capsules       Capsules

             Strength                                          Pack size
 0               5 mg                                            10 x 10
 1           0.3% w/v                                           1 x 5 ml
 2              25 mg                                             1 x 10
 3           21.8 gms                                           21.8 gms
 4   21.8 Gms , 20mg.  1 Kit contains 2 sachets of ORS 21.8 gms & 1x1...
 5              250mg                                              1 x 7
 6           0.3% w/v                                           1 x 5 ml
 7               20mg                                             1 x 10
 8        1%/0.1% w/v                                           1 x 5 ml
 9            200 mg.                                      10x10 Tablets
 10           400 mg.                                      10x10 Tablets
 11              20mg                                    10 x 10 Tablets
 12             150mg                                                1x1
 13             200mg                                                1x7
 14              50mg                                                1x7  ,
     Sr   Plant                          Brand name  \
 0    1   Waluj                           Allercrom
 1    2   Goa-I                           Amodep 10
 2    3   Goa-I                            Amodep 5
 3    4   Waluj                            Bactigen
 4    5   Waluj  Chloramphenicol 0.5% Eye Drops w/v
 5    6  Sinnar                            Electral

In [13]:
url ="https://www.fdcindia.com/"

df=pd.read_html(url,match="Dosage",header=0)[0]

In [14]:
df

,Sr,Plant,Brand name,Generic name,Dosage Form,Strength,Pack size
0,1,Waluj,Chloramphenicol Ophthalmic Solution 0.5% w/v,Chloramphenicol Ophthalmic Solution 0.5% w/v,Eye Drops,0.5% w/v,1x10 ml
1,2,Waluj,Dorzolamide 2% w/v Eye drops,Dorzolamide 2% w/v Eye drops,Eye Drops,2% w/v,1 x 5 ML
2,3,Waluj,"Dorzolamide 2% w/v, Timolol 0.5% w/v Eye Drops","Dorzolamide 2% w/v, Timolol 0.5% w/v Eye Drops",Eye Drops,"2%, 0.5% w/v",1 x 5 ML
3,4,Waluj,Dorzox,Dorzolamide 2% w/v Eye Drops,Eye Drops,2% w/v,1x5 ml
4,5,Waluj,Dorzox-T,Dorzolamide 2% and Timolol 0.5% Eye Drops,Eye Drops,"2%, 0.5% w/v",1x5 ml
5,6,Waluj,Duoprost,"Latanoprost 0.005% w/v, Timolol 0.5% w/v Eye D...",Eye Drops,"0.005% w/v, 0.5% w/v",1 x 2.5 ml
6,7,Waluj,Gentamycin 0.3% Eye drops w/v,Gentamycin 0.3% Eye drops w/v,Eye drops,0.3% w/v,1 x 5 ml
7,8,Waluj,Latanoprost 0.005% Ophthalmic Solution,Latanoprost 0.005% Ophthalmic Solution w/v,Eye Drops,0.005% w/v,1x2.5 ml
8,9,Waluj,"Latanoprost 0.005%, Timolol 0.5% Ophthalmic So...","Latanoprost 0.005%, Timolol 0.5% Ophthalmic So...",Eye Drops,"0.005% w/v, 0.5% w/v",1x2.5 ml
9,10,Sinnar,ORS 28.4 gms (Lime flavor),ORS 28.4 gms,Oral Granules,28.4 gms,4s
10,11,Sinnar,ORS 6.7 gms (Strawberry flavor),ORS 6.7 gms,Oral Granules,6.7 gms,30s
11,12,Waluj,Premoxin,Moxifloxacin 0.5% Eye Drops w/v,Eye Drops,0.5% w/v,1x5 ml
12,13,Waluj,Timolol Maleate 0.5% w/v,Timolol Maleate 0.5%,Eye Drops,0.5% w/v,1 x 5 ml

In [ ]:
pd.read_excel() #this could also read excel file
df_excel=pd.read_excel('df_excel') 
df_excel.to_pickle('df_excel')
pd.read_pickle('df_excel')

In [ ]:
# pd.read has alot of categories where we could work this was just an example to learn "how to use these panda features"